version: "3.9"

services:
  go_api:
    build: ./backend
    container_name: go_api
    ports:
      - "8080:8080"
    networks:
      - app-network

  react_app:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - go_api
    networks:
      - app-network

networks:
  app-network:
